//Functions

//criar um aplicativo de frases motivacionais

//Declaration - declaração da função
//function statament
function createPhrases(){
  console.log('Estudar é muito bom!')
  console.log('Paciência e persistência.')
  console.log('Revisão é mãe di aprendizado!')
}

//executar a função
// rodar, chamar, invocar
//execute, run, call, invoke

createPhrases()
createPhrases()
createPhrases()

//console.log('fim do programa')