/*
    Operadores condicional (Ternário)
*/

// Dependendo da condicao, nos receberemos valores diferentes

// Condicao entao valor 1 se nao valor 2
// condition ? value1 : value2

//Exemplos
//Cafe da manha top
/*
let pao = true
let queijo = true

const niceBreakfast = pao && queijo ? 'Cafe top' : 'Cafe ruim'
console.log(niceBreakfast)
*/

//Maior de 18
let age = 16
const canDrive = age >= 18 ? 'Can drive' : "Can't drive"
console.log(canDrive)
