/*
    Operadores Aritimeticos
*/

//multiplicacao *
//console.log(3.2 * 5.5)

//divisao /
//console.log(12 / 2)

//soma +
//console.log(34 + 67)

//subtracao -
//console.log(34 - 23)

//resto da divisao
let remainder
remainder = 11 % 11
//console.log(remainder)

//incremento
let increment = 0
increment++
//console.log(increment++)
//console.log(++increment)
//decremento
let decrement = 0
//console.log(--decrement)

//exponencial **
console.log(3 ** 2)


